### ISSUE TITLE
Moving to Buffer.from(...)

### ISSUE THREAD

**Issue by gabrielschulhof** [commenthol/mock-http#6]
`new Buffer(...)` is deprecated and unsafe. Would it be possible to migrate the code to `Buffer.from(...)`? [These places](https://github.com/commenthol/mock-http/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) are affected.

**Comment by commenthol** [comment]
Sure. Would you like to make a PR with the changes?

**Comment by commenthol** [comment]
Ok will change the things... PR is on its way...

**Comment by commenthol** [comment]
v1.0.0 published
